export var AccentColor = '#FFBD20'
export var SecondaryAccentColor = '#4F5154'
export var AccentColor1 = AccentColor
export var AccentColor2 = '#e8e8e8'
export var ButtonAccentColor = AccentColor
export var ScreenBackgroundColor0 = '#FCFDFF'
export var ScreenBackgroundColor1 = AccentColor
export var ScreenBackgroundColor2 = '#fff'
export var ScreenBackgroundColor3 = '#f9f9f9'
export var HeaderColor0 = '#fff'
export var CardColor0 = '#fff'
export var CardColor1 = '#fff'
export var CardColor2 = '#CBDCFF'
export var CardColor3 = '#F5F7F9'
export var CardColor4 = '#F5F7F9'
export var DisabledCardColor = '#E9EBF0'
export var TextColor0 = '#474C58'
export var TextColor1 = '#fff'
export var TextColor2 = '#868FA0'
export var TextColor3 = '#797979'
export var TextColor4 = '#868FA0'
export var TextColor5 = AccentColor
export var Glass1 = 'rgba(255,255,255,0.65)'
export var Glass2 = 'rgba(255,255,255,0.25)'
export var GlassBorder = '#fff'

export var HeaderText1 = '#09193A'
export var HeaderText2 = '#474C58'
export var HeaderText3 = '#313A4E'
export var SecondaryButtonColor = 'rgba(66, 103, 179, 0.1)'
export var SecondaryButtonColor1 = '#F5F7F9'
export var BorderColor1= '#797979'
export var ButtonColor1= '#fff'
export var DisableButtonColor = '#e8e8e8'
export var IconColor1 =AccentColor
export var IconColor2 =SecondaryAccentColor
export var Green = '#03C071'
export var Red = '#EB5757'
export var Orange = '#F17C4D'
